### ISSUE TITLE
Hitting error callback on Set even though it succeeds

### ISSUE THREAD

**Issue by stechnique** [Geotab/mygeotab-php#1]
See here:
https://community.geotab.com/s/question/0D52J00007WKQBvSAP/error-codes-on-set
I would blame line 200 in API.php:

`} else if (count($result) == 0) {`

count($result) will never be 0 if we get the _jsonrpc:2.0_ key/value pair. So maybe change that logic to count($result) == 1, but I think it's safer to actually proceed by making sure $result['error'] does not exist. I will leave it up to you to decide which is why I'm not doing a PR myself.

**Comment by bhoyle** [comment]
(I am original poster in community thread above)

I changed line 206 of the API local copy to the following and tested with both a properly formed request and a request with an error. For this limited test it worked as it should. 
`    } elseif(array_key_exists("error", $result)) {`

**Comment by colonelchlorine** [comment]
Resolved in 1.2.0. Checks for error first, otherwise returns/callbacks result. If $result["result"] isn't defined then it will return null. Similar to our JS API.

**Comment by bhoyle** [comment]
👍
