### ISSUE TITLE
Certificate validation is currently disabled

### ISSUE THREAD

**Issue by stechnique** [Geotab/mygeotab-php#2]
See here:
https://github.com/Geotab/mygeotab-php/blob/5098fcb4b2ff335092cd3449778179c141461476/src/Geotab/API.php#L186

`verify: false` is insecure in itself, the default CA should be able to verify the integrity of Geotab certificates and should work just fine if changed to true. Testing needed.

[http://docs.guzzlephp.org/en/stable/request-options.html#verify](http://docs.guzzlephp.org/en/stable/request-options.html#verify)

**Comment by colonelchlorine** [comment]
Resolved this, tested it from fresh machine, and it works
Edit: Thanks!
